{% set version = "0.33-dev" %}

package:
  name: larray-editor
  version: {{ version }}

source:
  git_tag: {{ version }}
  git_url: https://github.com/larray-project/larray-editor.git

build:
  noarch: python
  number: 0
  entry_points:
    - larray-editor = larray_editor.start:main

requirements:
  host:
    - python
    - pip

  run:
    - python
    # requires larray >= 0.32 because of the LArray -> Array rename
    - larray >=0.32
    - matplotlib
    # excluded versions 5.0 and 5.1.0 of ipykernel because these versions make the console useless after any exception
    # https://github.com/larray-project/larray-editor/issues/166
    - ipykernel !=5.0,!=5.1.0
    # jupyter_client >=6.0 is incompatible with ipykernel <5.2 but ipykernel 5.2 is not available yet on anaconda
    # https://github.com/larray-project/larray-editor/issues/209
    - jupyter_client <6
    - pyqt >=4.6  # for API v2
    - qtpy

test:
  imports:
    - larray_editor

app:
  entry: larray-editor
  # icon: larray.png
  summary: "Graphical User Interface for LArray"
  type: desk

about:
  home: https://github.com/larray-project/larray-editor
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: "Graphical User Interface for LArray"
  dev_url: https://github.com/larray-project/larray-editor

extra:
  recipe-maintainers:
    - alixdamman
    - gdementen
