{% set version = "0.34" %}

package:
  name: larray-editor
  version: {{ version }}

source:
  git_tag: {{ version }}
  git_url: https://github.com/larray-project/larray-editor.git

build:
  noarch: python
  number: 0
  entry_points:
    - larray-editor = larray_editor.start:main

requirements:
  host:
    - python >=3.7
    - pip

  run:
    - python >=3.7
    # requires larray >= 0.32 because of the LArray -> Array rename
    - larray >=0.32
    - matplotlib
    - pyqt >=5
    - qtpy >=2  # for Qt6 support
    # jedi >=0.18 to workaround incompatibility between jedi <0.18 and parso >=0.8 (see #220)
    - jedi >=0.18

test:
  imports:
    - larray_editor

app:
  entry: larray-editor
  # icon: larray.png
  summary: "Graphical User Interface for LArray"
  type: desk

about:
  home: https://github.com/larray-project/larray-editor
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: "Graphical User Interface for LArray"
  dev_url: https://github.com/larray-project/larray-editor

extra:
  recipe-maintainers:
    - alixdamman
    - gdementen
