{% set version = "0.35" %}

package:
  name: larray-editor
  version: {{ version }}

source:
  git_tag: {{ version }}
  git_url: https://github.com/larray-project/larray-editor.git

build:
  noarch: python
  number: 0
  entry_points:
    - larray-editor = larray_editor.start:main

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools

  run:
    - python >=3.9
    # Technically, we should require larray >=0.35 because we need align_arrays
    # for compare(), but to make larray-editor releasable, we cannot depend on
    # larray X.Y when releasing larray-editor X.Y (see utils.py for more
    # details)
    # TODO: require 0.35 for next larray-editor version
    - larray >=0.32
    # it is indirectly pulled from larray, but let us be explicit about this
    - numpy >=1.22
    - matplotlib
    - pyqt >=5
    - qtpy >=2  # for Qt6 support
    - qt >=5.11
    # jedi >=0.18 to workaround incompatibility between jedi <0.18 and parso >=0.8 (see #220)
    - jedi >=0.18
    - qtconsole !=5.4.2

test:
  imports:
    - larray_editor

app:
  entry: larray-editor
  # icon: larray.png
  summary: "Graphical User Interface for LArray"
  type: desk

about:
  home: https://github.com/larray-project/larray-editor
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: "Graphical User Interface for LArray"
  dev_url: https://github.com/larray-project/larray-editor

extra:
  recipe-maintainers:
    - alixdamman
    - gdementen
