.. py:currentmodule:: larray_editor

.. _misc_editor:

Miscellaneous improvements
^^^^^^^^^^^^^^^^^^^^^^^^^^

* added keyword arguments ``rtol``, ``atol`` and ``nans_equal`` to the :py:obj:`compare()` function
  (closes :editor_issue:`172`).

* Sizes of the main window and the resizable components are saved when closing the viewer and restored
  when the viewer is reopened (closes :editor_issue:`165`).


Fixes
^^^^^

* fixed something (closes :editor_issue:`1`).
